import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NavbarWrapper from "./NavbarWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    
    <html lang="en">
      <body className="min-h-screen bg-zinc-950 ">
        <div className="min-h-screen flex flex-col">
          <NavbarWrapper>
            {children}
          </NavbarWrapper>
        </div>
      </body>
    </html>
  );
}
